=== AdrianJS2009/DAW/Lenguaje de Marcas/listado.dtd
<!ELEMENT listado (futuro+, divisa+, bono+, letra+)>
<!ATTLIST valor futuro CDATA #REQUIRED>
<!ATTLIST valor divisa CDATA #REQUIRED>
<!ATTLIST bono precio CDATA #REQUIRED>
<!ATTLIST valor letra CDATA #REQUIRED>
<!ELEMENT ciudad_procedencia (madrid|nyork|frankfurt|tokio)>
<!ELEMENT Madrid EMPTY>
<!ELEMENT NuevaYork EMPTY>
<!ELEMENT Frankfurt EMPTY>
<!ELEMENT Tokio EMPTY>
<!ATTLIST divisa estable CDATA #IMPLIED>
<!ATTLIST bono estable CDATA #IMPLIED>
<!ELEMENT futuro (producto, mercado?, ciudad_procedencia)>
<!ELEMENT producto (#PCDATA)>
<!ELEMENT mercado (#PCDATA)>
<!ELEMENT bono (pais_de_procedencia,valor_deseado, valor_minimo, valor_maximo, ciudad_procedencia)>
<!ELEMENT valor_deseado (#PCDATA)>
<!ELEMENT valor_minimo (#PCDATA)>
<!ELEMENT valor_maximo (#PCDATA)>
<!ELEMENT pais_de_procedencia (#PCDATA)>
<!ELEMENT divisa (nombre_divisa, tipo_de_cambio+, ciudad_procedencia)>
<!ELEMENT nombre_divisa (#PCDATA)>
<!ELEMENT tipo_de_cambio (#PCDATA)>
<!ELEMENT letra (tipo_de_interes, pais_emisor,ciudad_procedencia)>
<!ELEMENT tipo_de_interes (#PCDATA)>
<!ELEMENT pais_emisor (españa|eeuu|alemania|japon)>
<!ELEMENT España     EMPTY>
<!ELEMENT EEUU        EMPTY>
<!ELEMENT Alemania     EMPTY>
<!ELEMENT Japón       EMPTY>

=== AdrianJS2009/DAW/Lenguaje de Marcas/Tema 1/listado de mercados.xml
<?xml version="1.0"?>
<!DOCTYPE listado SYSTEM "listado.dtd">

<listado>
  <futuro precio="12.59">
    <producto>Salchichas</producto>
    <mercado>Europa</mercado>
    <ciudad_procedencia>
      <Frankfurt/>
    </ciudad_procedencia>
  </futuro>
  <divisa precio="1698">
    <nombre_divisa>Euro</nombre_divisa>
    <tipo_de_cambio>2.1:1 euros</tipo_de_cambio>
    <tipo_de_cambio>1:0.87 dólares</tipo_de_cambio>
    <ciudad_procedencia>
      <Madrid/>
    </ciudad_procedencia>
  </divisa>
  <bono precio="19240" estable="no">
    <pais_de_procedencia>
      Marruecos
    </pais_de_procedencia>
    <valor_deseado>1250</valor_deseado>
    <valor_minimo>3981</valor_minimo>
    <valor_maximo>18090</valor_maximo>
    <ciudad_procedencia>
      <Tokio/>
    </ciudad_procedencia>
  </bono>
  <letra precio="96310">
    <tipo_de_interes>7.91%</tipo_de_interes>
    <pais_emisor>
      <España/>
    </pais_emisor>
    <ciudad_procedencia>
      <Madrid/>
    </ciudad_procedencia>
  </letra>
</listado>
