=== AdrianJS2009/DAW/Lenguaje de Marcas/Examen 23-02-23/examen_JimenezSantiago_Adrian2.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
  targetNamespace="inventario"
  xmlns="https://www.ejemplo.com"
  elementFormDefault="qualified">

  <xs:element name="inventario">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="objeto" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="mesa">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="tipo" type="xs:string"/>
                    <xs:element name="localizacion" type="xs:string"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="ordenador">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="procesador">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute name="fabricante" type="xs:string"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="memoria">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute name="valor" type="xs:string"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="discoduro" type="xs:string"/>
                  </xs:sequence>

=== AdrianJS2009/DAW/Lenguaje de Marcas/Examen 23-02-23/examen_JimenezSantiago_Adrian2.xml
<?xml version="1.0" encoding="UTF-8"?>
<inventario xmlns="https://www.ejemplo.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://www.ejemplo.com examen_JimenezSantiago_Adrian2.xsd"></inventario>
<inventario>
      <inventario>
        <objeto codigo ="C001">
			<mesa>
			<tipo>Modular</tipo>
			<localizacion>España</localizacion>
			</mesa>
			<ordenador>
			<procesador fabricante ="AMD">Ryzen 6
			</procesador>
			<memoria valor ="MB">516</memoria>
			<discoduro>HDD</discoduro>
			</ordenador>
		</objeto>
</inventario>
