<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE listafacturas [

<!ELEMENT listafacturas (factura+)>
<!ELEMENT factura (emisor, pagador, importe)>
<!ATTLIST factura fecha CDATA #IMPLIED>
<!ELEMENT emisor (nombre, volumenventas?)>
<!ATTLIST emisor cif CDATA #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT volumenventas (#PCDATA)>
<!ELEMENT pagador (nombre, volumenventas?)>
<!ATTLIST pagador cif CDATA #REQUIRED>
<!ELEMENT importe (#PCDATA)>
]>

<listafacturas>
    <factura fecha="2015-01-01">
        <emisor cif="A12345678">
            <nombre>Empresa 1</nombre>
            <volumenventas>1000000</volumenventas>
        </emisor>
        <pagador cif="B12345678">
            <nombre>Empresa 2</nombre>
        </pagador>
        <importe>1000</importe>
    </factura>
    <factura>
        <emisor cif="A12345678">
            <nombre>Empresa 1</nombre>
            <volumenventas>1000000</volumenventas>
        </emisor>
        <pagador cif="B12345678">
            <nombre>Empresa 2</nombre>
        </pagador>
        <importe>1000</importe>
    </factura>
    <factura fecha="2015-01-01">
        <emisor cif="A12345678">
            <nombre>Empresa 1</nombre>
            <volumenventas>1000000</volumenventas>
        </emisor>
        <pagador cif="B12345678">
            <nombre>Empresa 2</nombre>
        </pagador>
        <importe>1000</importe>
    </factura>
</listafacturas>
