<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE listaventas [
    <!ELEMENT listaventas (venta+)>
<!ELEMENT venta (importe, comprador, vendedor, fecha?,codigo)>
<!ELEMENT importe (#PCDATA)>
<!ELEMENT comprador (#PCDATA)>
<!ELEMENT vendedor (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT codigo (#PCDATA)>
]>

<listaventas>
    <venta>
        <importe>1000</importe>
        <comprador>Jose</comprador>
        <vendedor>Pepe</vendedor>
        <codigo>1</codigo>
    </venta>
    <venta>
        <importe>2000</importe>
        <comprador>Jose</comprador>
        <vendedor>Pepe</vendedor>
        <fecha>2018-01-01</fecha>
        <codigo>2</codigo>
    </venta>
</listaventas>
