=== AdrianJS2009/DAW/Lenguaje de Marcas/Tema 1/JimenezSantiago_Adrian_ejercicio_final_1.dtd
<!ELEMENT pedido (sucursal, trabajador, fecha, observaciones, plazo, artículos+)>
<!ELEMENT sucursal (direccion+)>
<!ATTLIST sucursal codigo CDATA #REQUIRED>
<!ELEMENT direccion (#PCDATA)>
<!ELEMENT trabajador (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT observaciones (#PCDATA)>
<!ELEMENT plazo (#PCDATA)>
<!ELEMENT artículos (artículo+)>
<!ELEMENT artículo (#PCDATA)>
<!ATTLIST artículo codigo CDATA #REQUIRED>
<!ATTLIST artículo unidades CDATA #REQUIRED>
<!ATTLIST artículo precio CDATA #REQUIRED>
<!ATTLIST artículo observaciones CDATA #IMPLIED>

=== AdrianJS2009/DAW/Lenguaje de Marcas/Tema 1/JimenezSantiago_Adrian_ejercicio_final_2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pedido SYSTEM "JimenezSantiago_Adrian_ejercicio_final_1.dtd">


<pedido>
    <sucursal codigo="001">
        <direccion>Calle 123</direccion>
        <direccion>Ciudad XYZ</direccion>
    </sucursal>
    <trabajador>Pepito de Los Campos</trabajador>
    <fecha>2022-12-31</fecha>
    <observaciones>Ninguna</observaciones>
    <plazo>7 días</plazo>
    <artículos>
        <artículo codigo="A001" unidades="2" precio="100">Artículo 1</artículo>
        <artículo codigo="A002" unidades="3" precio="200">Artículo 2</artículo>
    </artículos>
</pedido>
